# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f55145bec60696e2e42b8b9977f2f6672f53fcbe8b950f41c3a24588373389f660b740b4f55781e1d68b9019dbe084e2fd684d5bd8b95e4028810ae2fbf964f

test:
  secret_key_base: b86815f5c9dbf7dfefefa40e7be50c8404b5ce9ed036cf2d29c91b9a6302f272e95489ab06e6a65e896fd2e751117cd4515d34a160807f074a02f1b981c78ef5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
